version: '3.8'

services:
  veillepi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veillepi-prod
    ports:
      - "2001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: always
    command: sh -c "npm run start"